[package]
org = "wso2hc"
name = "facility_registry"
version = "1.0.0"
distribution = "2201.12.11"
authors = ["WSO2"]
keywords = ["Healthcare", "FHIR", "r4", "mCSD", "FacilityRegistry"]

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
artifactId = "h2"
version = "2.3.232"
groupId = "com.h2database"

[[platform.java21.dependency]]
artifactId = "postgresql"
version = "42.7.9"
groupId = "org.postgresql"

