// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).

// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// AUTO-GENERATED FILE.
//
// This file is auto-generated by Ballerina.
// Developers are allowed to modify this file as per the requirement.

import facility_registry.handlers;
import facility_registry.r4_api_config;

import ballerina/http;
import ballerina/log;
import ballerina/time;
import ballerinax/health.fhir.r4;
import ballerinax/health.fhirr4;
import ballerinax/health.fhir.r4.international401;
import ballerinax/health.fhir.r4.parser as fhirParser;
import ballerinax/health.fhir.r4.validator;
import ballerinax/java.jdbc;

configurable string serverName = "OpenHIE Facility Registry";

// ── Audit Service integration ─────────────────────────────────────────────
// Leave empty to disable auditing (zero behaviour change for existing deployments)
configurable string auditServiceUrl = "";

// ── IHE Transaction Flags ─────────────────────────────────────────────────
// ITI-90  Find Matching Care Services (Search / Read)
configurable boolean iti90Enabled = true;
// ITI-91  Request Care Services Updates (History)
configurable boolean iti91Enabled = true;
// ITI-130 Maintain Care Services (Create / Update / Delete)
configurable boolean iti130Enabled = true;

# Generic types to wrap all implemented profiles for each resource.
# Add required profile types here.
public type Endpoint international401:Endpoint;

public type Parameters international401:Parameters;

public type Organization international401:Organization;

public type OrganizationAffiliation international401:OrganizationAffiliation;

public type HealthcareService international401:HealthcareService;

public type Location international401:Location;

// Global Database Config Objects
final handlers:DBHandler dbHandler = check new handlers:DBHandler();
final jdbc:Client jdbcClient = check dbHandler.initializeJdbcClient();

// Audit Service HTTP client — nil when auditServiceUrl is empty
final http:Client? auditClient = auditServiceUrl != "" ? checkpanic new (auditServiceUrl) : ();


function init() returns error? {
    boolean|error? dbStatus = dbHandler.initDatabase(jdbcClient);
    if (dbStatus is boolean && dbStatus == true) {
        log:printInfo("DB Init Successfully");
    }

    // Load all StructureDefinitions from database and register them in FHIR registry
    error? profileLoadStatus = loadCustomProfiles();
    if (profileLoadStatus is error) {
        log:printError("Failed to load custom profiles: " + profileLoadStatus.message());
    }

    log:printInfo("FHIR Server started successfully");
}

listener http:Listener httpListener = http:getDefaultListener();

// Returns a 405 FHIRError when the given IHE transaction is disabled.
isolated function checkTransactionEnabled(boolean enabled, string transactionName) returns r4:FHIRError? {
    if !enabled {
        return r4:createFHIRError(
            string `IHE transaction ${transactionName} is disabled on this server`,
            r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_METHOD_NOT_ALLOWED
        );
    }
    return ();
}

# initialize source system endpoints here

service http:Service /fhir/r4/metadata on httpListener {

    # The capability statement is a key part of the overall conformance framework in FHIR. It is used as a statement of the
    # features of actual software, or of a set of rules for an application to provide. This statement connects to all the
    # detailed statements of functionality, such as StructureDefinitions and ValueSets. This composite statement of application
    # capability may be used for system compatibility testing, code generation, or as the basis for a conformance assessment.
    # For further information https://hl7.org/fhir/capabilitystatement.html
    # + return - capability statement as a json
    isolated resource function get .() returns r4:CapabilityStatement|error {
        return check r4:generateFHIRCapabilityStatement();
    }
}

// Load all StructureDefinition resources from database and register them in FHIR registry
function loadCustomProfiles() returns error? {
    log:printInfo("Loading custom profiles from database...");

    handlers:ReadHandler readHandler = new handlers:ReadHandler();
    json|error allStructureDefinitions = readHandler.readAllResources(jdbcClient, "StructureDefinition", ());

    if allStructureDefinitions is error {
        log:printError("Failed to read StructureDefinitions from database: " + allStructureDefinitions.message());
        return allStructureDefinitions;
    }

    // Parse the Bundle response
    r4:Bundle|error bundle = fhirParser:parse(allStructureDefinitions).ensureType();
    if bundle is error {
        log:printError("Failed to parse StructureDefinition bundle: " + bundle.message());
        return bundle;
    }

    // Process each StructureDefinition entry
    int registeredCount = 0;
    r4:BundleEntry[]? entries = bundle.entry;
    if entries is r4:BundleEntry[] {
        foreach var entry in entries {
            anydata|r4:FHIRWireFormat resourceField = entry?.'resource;
            if resourceField is () {
                continue;
            }

            // Try to get JSON representation for field access
            json|error resourceJson = trap resourceField.toJson();
            if resourceJson is error {
                log:printWarn("Failed to convert StructureDefinition to JSON: " + resourceJson.message());
                continue;
            }

            string|error urlResult = resourceJson.url.ensureType(string);
            string|error typeResult = resourceJson.'type.ensureType(string);

            if urlResult is error || typeResult is error {
                log:printWarn("Skipping StructureDefinition without url or type");
                continue;
            }

            string customUrl = urlResult;
            string resourceType = typeResult;

            // Register the profile in FHIR registry using the same structure as POST endpoint
            readonly & r4:Profile customProfile = {
                url: customUrl,
                resourceType: resourceType,
                modelType: json
            }.cloneReadOnly();

            readonly & r4:IGInfoRecord customIG = {
                title: "Custom Profiles IG",
                name: "custom-profiles",
                terminology: {
                    codeSystems: [],
                    valueSets: []
                },
                profiles: {
                    [customUrl]: customProfile
                },
                searchParameters: []
            }.cloneReadOnly();

            r4:FHIRImplementationGuide ig = new (customIG);
            r4:FHIRError? regResult = r4:fhirRegistry.addImplementationGuide(ig);

            if regResult is r4:FHIRError {
                log:printWarn(string `Failed to register profile ${customUrl}: ${regResult.message()}`);
            } else {
                registeredCount += 1;
                log:printDebug(string `Registered profile: ${customUrl} for resource type: ${resourceType}`);
            }
        }
    }

    log:printInfo(string `Successfully loaded and registered ${registeredCount} custom profile(s) from database`);
    return;
}

isolated function performResourceSearch(string resourceType, r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Search - Start Execution!`);
    do {
        // Access query parameters from FHIRContext
        map<r4:RequestSearchParameter[]> searchParams = fhirContext.getRequestSearchParameters();

        // Convert RequestSearchParameter[] to string[] for handler
        map<string[]> queryParams = {};
        foreach var [key, values] in searchParams.entries() {
            string[] paramValues = [];
            foreach var param in values {
                paramValues.push(param.value);
            }
            queryParams[key] = paramValues;
        }

        // Access pagination context
        r4:PaginationContext? paginationContext = fhirContext.getPaginationContext();

        // Use ReadHandler to search resources
        handlers:ReadHandler readHandler = new handlers:ReadHandler();
        json|error searchResult = readHandler.searchResources(jdbcClient, resourceType, queryParams, paginationContext);

        if searchResult is json {
            log:printDebug(string `${resourceType}: Search - Execution Success!`);
            r4:Bundle bundle = check fhirParser:parse(searchResult).ensureType();
            sendAuditEvent(resourceType, "", "E", "search", "0", "");
            return bundle;
        } else {
            string errorMsg = searchResult.message();
            log:printError("Search failed: " + errorMsg);
            sendAuditEvent(resourceType, "", "E", "search", "8", errorMsg);
            return r4:createFHIRError(string `Failed to search ${resourceType}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError("Error processing search: " + e.message());
        return r4:createFHIRError(
                "Search operation failed.", r4:ERROR, r4:INFORMATIONAL, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to handle delete operations for resources
isolated function performResourceDelete(string resourceType, string id) returns r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Delete - Start Execution!`);
    do {
        handlers:DeleteHandler deleteHandler = new handlers:DeleteHandler(jdbcClient);
        boolean|error result = deleteHandler.deleteResourceWithTransaction(resourceType, id);

        if result is boolean && result {
            log:printDebug(string `${resourceType}: DELETE - Execution Success!`);
            sendAuditEvent(resourceType, id, "D", "delete", "0", "");
            return {
                resourceType: "OperationOutcome",
                issue: [
                    {
                        severity: "information",
                        code: "informational",
                        diagnostics: string `${resourceType}/${id} deleted successfully`
                    }
                ]
            };
        } else {
            string errorMsg = result is error ? result.message() : "Unknown error";
            log:printError(string `Delete failed: ${errorMsg}`);
            sendAuditEvent(resourceType, id, "D", "delete", "8", errorMsg);

            // Check if resource was not found
            if errorMsg.includes("not found") {
                return r4:createFHIRError(string `${resourceType}/${id} not found`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_NOT_FOUND);
            }

            return r4:createFHIRError(string `Failed to delete ${resourceType}/${id}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }

    } on fail error e {
        log:printError(string `Error deleting ${resourceType}/${id}: ${e.message()}`);
        return r4:createFHIRError(string `Delete operation failed.`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
    }
}

// Utility function to handle resource history retrieval for a specific resource ID
isolated function performResourceHistory(string resourceType, string id) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: History - Start Execution for ID: ${id}`);
    do {
        handlers:HistoryHandler historyHandler = new handlers:HistoryHandler(jdbcClient);
        map<json>[]|error result = historyHandler.getResourceHistory(resourceType, id);

        if result is map<json>[] {
            r4:BundleEntry[] entries = [];
            foreach map<json> historyItem in result {
                string operation = historyItem.get("operation").toString();
                string lastModifiedStr = historyItem.get("lastModified").toString();

                r4:BundleEntry entry = {
                    request: {
                        method: <r4:HTTPVerb>operation,
                        url: string `${resourceType}/${id}`
                    },
                    response: {
                        status: "200",
                        lastModified: lastModifiedStr
                    }
                };

                // For DELETE operations, do not include the resource
                if operation != "DELETE" {
                    json resourceData = historyItem.get("resource");
                    entry.'resource = resourceData;
                }

                entries.push(entry);
            }

            r4:Bundle bundle = {
                resourceType: "Bundle",
                'type: "history",
                total: entries.length(),
                entry: entries
            };

            log:printDebug(string `Retrieved ${entries.length()} versions for ${resourceType}/${id}`);
            sendAuditEvent(resourceType, id, "E", "history", "0", "");
            return bundle;
        } else {
            string errorMsg = result.message();
            log:printError(string `Failed to retrieve history: ${errorMsg}`);
            sendAuditEvent(resourceType, id, "E", "history", "8", errorMsg);
            return r4:createFHIRError(errorMsg, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError(string `Error retrieving ${resourceType}/${id}/_history: ${e.message()}`);
        return r4:createFHIRError(e.message(), r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to handle all resource history retrieval for a resource type
isolated function performAllResourceHistory(string resourceType) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: All History - Start Execution`);
    do {
        handlers:HistoryHandler historyHandler = new handlers:HistoryHandler(jdbcClient);
        map<json>[]|error result = historyHandler.getAllHistory(resourceType);

        if result is map<json>[] {
            r4:BundleEntry[] entries = [];
            foreach map<json> historyItem in result {
                string operation = historyItem.get("operation").toString();
                string lastModifiedStr = historyItem.get("lastModified").toString();
                json resourceData = historyItem.get("resource");
                json resourceIdJson = check resourceData.id;
                string resourceId = resourceIdJson.toString();

                r4:BundleEntry entry = {
                    request: {
                        method: <r4:HTTPVerb>operation,
                        url: string `${resourceType}/${resourceId}`
                    },
                    response: {
                        status: "200",
                        lastModified: lastModifiedStr
                    }
                };

                // For DELETE operations, do not include the resource
                if operation != "DELETE" {
                    entry.'resource = resourceData;
                }

                entries.push(entry);
            }

            r4:Bundle bundle = {
                resourceType: "Bundle",
                'type: "history",
                total: entries.length(),
                entry: entries
            };

            log:printDebug(string `Retrieved ${entries.length()} total history entries for ${resourceType}`);
            sendAuditEvent(resourceType, "", "E", "history", "0", "");
            return bundle;
        } else {
            string errorMsg = result.message();
            log:printError(string `Failed to retrieve all history: ${errorMsg}`);
            sendAuditEvent(resourceType, "", "E", "history", "8", errorMsg);
            return r4:createFHIRError(errorMsg, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError(string `Error retrieving ${resourceType}/_history: ${e.message()}`);
        return r4:createFHIRError(e.message(), r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to convert resource result to typed resource
isolated function convertToTypedResource(any|r4:OperationOutcome|r4:FHIRError result, typedesc<anydata> resourceType, string resourceName) returns anydata|r4:OperationOutcome|r4:FHIRError {
    if result is r4:OperationOutcome|r4:FHIRError {
        return result;
    } else if result is anydata && !(result is json) {
        return result;
    } else {
        json jsonResult = <json>result;
        anydata|error typedResult = jsonResult.cloneWithType(resourceType);
        if typedResult is error {
            return r4:createFHIRError(string `Invalid ${resourceName} resource structure`, r4:CODE_SEVERITY_ERROR, r4:PROCESSING);
        }
        return typedResult;
    }
}

// Utility function to handle resource read by ID operations
isolated function performResourceRead(string resourceType, string id) returns any|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Read - Start Execution for ID: ${id}`);
    do {
        handlers:ReadHandler readHandler = new handlers:ReadHandler();
        json|error result = readHandler.readResource(jdbcClient, resourceType, id);

        if result is json {
            log:printDebug(string `${resourceType}: READ - Execution Success!`);
            any parsedResource = check fhirParser:parse(result).ensureType();
            sendAuditEvent(resourceType, id, "R", "read", "0", "");
            return parsedResource;
        } else {
            string errorMsg = result.message();
            log:printError(string `Read failed: ${errorMsg}`);
            sendAuditEvent(resourceType, id, "R", "read", "8", errorMsg);

            // Check if resource was not found
            if errorMsg.includes("not found") {
                return r4:createFHIRError(string `${resourceType}/${id} not found`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_NOT_FOUND);
            }

            return r4:createFHIRError(string `Failed to fetch ${resourceType}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError(string `Error processing ${resourceType}: ${e.message()}`);
        return r4:createFHIRError(string `Invalid ${resourceType} data`, r4:ERROR, r4:INFORMATIONAL, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to handle resource version read by ID and version ID operations
isolated function performResourceVersionRead(string resourceType, string id, string vid) returns any|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Version Read - Start Execution for ID: ${id}, Version: ${vid}`);
    do {
        handlers:HistoryHandler historyHandler = new handlers:HistoryHandler(jdbcClient);
        int versionId = check int:fromString(vid);
        map<json>|error result = historyHandler.getResourceVersion(resourceType, id, versionId);

        if result is map<json> {
            // Extract just the resource from the map
            json resourceData = result.get("resource");
            log:printDebug(string `${resourceType}: VERSION READ - Execution Success! Retrieved ${resourceType}/${id}/_history/${vid}`);
            any parsedResource = check fhirParser:parse(resourceData).ensureType();
            return parsedResource;
        } else {
            string errorMsg = result.message();
            log:printError(string `Failed to retrieve version: ${errorMsg}`);
            return r4:createFHIRError(errorMsg, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_NOT_FOUND);
        }
    } on fail error e {
        log:printError(string `Error retrieving ${resourceType}/${id}/_history/${vid}: ${e.message()}`);
        return r4:createFHIRError("Error retrieving history", r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to handle resource creation operations
isolated function performResourceCreate(string resourceType, json resourceJson) returns any|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Create - Start Execution`);
    do {
        handlers:CreateHandler createHandler = new handlers:CreateHandler(jdbcClient);
        json|error? result = createHandler.saveResourceWithTransaction(resourceType, resourceJson);

        if result is json {
            log:printDebug(string `${resourceType}: POST - Execution Success!`);
            any parsedResource = check fhirParser:parse(result).ensureType();
            json idJson = check result.id;
            string createdId = idJson.toString();
            sendAuditEvent(resourceType, createdId, "C", "create", "0", "");
            return parsedResource;
        } else {
            string errorMsg = result is error ? result.message() : "Unknown error";
            log:printError(string `Resource save failed: ${errorMsg}`);
            sendAuditEvent(resourceType, "", "C", "create", "8", errorMsg);

            // mCSD / FHIR base validation failure → 422 Unprocessable Entity
            if errorMsg.startsWith("[FHIR_VALIDATION]") || errorMsg.startsWith("[MCSD_VALIDATION]") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_UNPROCESSABLE_ENTITY);
            }

            // Check if resource already exists (duplicate ID)
            if errorMsg.includes("already exists") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_CONFLICT);
            }

            // Check if error is an unresolved reference (FK violation translated in create_handler)
            if errorMsg.includes("Unresolved reference") || errorMsg.includes("violates foreign key constraint") || errorMsg.includes("FK_REFERENCES_TARGET") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_UNPROCESSABLE_ENTITY);
            }

            // Check if error is related to invalid references (validation failure)
            if errorMsg.includes("does not exist") || errorMsg.includes("Invalid reference") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
            }

            // Check for missing required fields
            if errorMsg.includes("KeyNotFound") || errorMsg.includes("must have an 'id' field") {
                return r4:createFHIRError("Required field missing in resource (resource must have an 'id' field when server-generated IDs are disabled)", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
            }

            // Otherwise it's a server/database error
            return r4:createFHIRError("Internal server error", r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError(string `Error processing ${resourceType}: ${e.message()}`);
        return r4:createFHIRError(string `Invalid ${resourceType} data: ${e.message()}`, r4:ERROR, r4:INFORMATIONAL, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to handle resource update operations
isolated function performResourceUpdate(string resourceType, string id, json resourceJson) returns any|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Update - Start Execution for ID: ${id}`);
    do {
        handlers:UpdateHandler updateHandler = new handlers:UpdateHandler(jdbcClient);
        string|error result = updateHandler.updateResourceWithTransaction(resourceType, id, resourceJson);

        if result is string {
            log:printDebug(string `${resourceType}: PUT - Execution Success!`);
            any parsedResource = check fhirParser:parse(resourceJson).ensureType();
            sendAuditEvent(resourceType, id, "U", "update", "0", "");
            return parsedResource;
        } else {
            string errorMsg = result.message();
            log:printError(string `Update failed: ${errorMsg}`);
            sendAuditEvent(resourceType, id, "U", "update", "8", errorMsg);

            // mCSD / FHIR base validation failure → 422 Unprocessable Entity
            if errorMsg.startsWith("[FHIR_VALIDATION]") || errorMsg.startsWith("[MCSD_VALIDATION]") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_UNPROCESSABLE_ENTITY);
            }

            // Check if resource was not found
            if errorMsg.includes("not found") {
                return r4:createFHIRError(string `${resourceType}/${id} not found`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_NOT_FOUND);
            }

            // Check if error is an unresolved reference (FK violation)
            if errorMsg.includes("Unresolved reference") || errorMsg.includes("violates foreign key constraint") || errorMsg.includes("FK_REFERENCES_TARGET") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_UNPROCESSABLE_ENTITY);
            }

            // Check if error is related to invalid references (validation failure)
            if errorMsg.includes("does not exist") || errorMsg.includes("Invalid reference") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
            }

            // Otherwise it's a server/database error
            return r4:createFHIRError(string `Failed to update ${resourceType}/${id}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError(string `Error updating ${resourceType}/${id}: ${e.message()}`);
        return r4:createFHIRError(string `Update operation failed: ${e.message()}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Utility function to handle resource patch operations
isolated function performResourcePatch(string resourceType, string id, json patch) returns any|r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Patch - Start Execution for ID: ${id}`);
    do {
        handlers:UpdateHandler updateHandler = new handlers:UpdateHandler(jdbcClient);
        json|error result = updateHandler.patchResourceWithTransaction(resourceType, id, patch);

        if result is json {
            log:printDebug(string `${resourceType}: PATCH - Execution Success!`);
            any parsedResource = check fhirParser:parse(result).ensureType();
            return parsedResource;
        } else {
            string errorMsg = result.message();
            log:printError(string `Patch failed: ${errorMsg}`);

            // Check if error is an unresolved reference (FK violation)
            if errorMsg.includes("Unresolved reference") || errorMsg.includes("violates foreign key constraint") || errorMsg.includes("FK_REFERENCES_TARGET") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_UNPROCESSABLE_ENTITY);
            }

            // Check if error is related to invalid references (validation failure)
            if errorMsg.includes("does not exist") || errorMsg.includes("Invalid reference") {
                return r4:createFHIRError(errorMsg, r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
            }

            // Otherwise it's a server/database error
            return r4:createFHIRError(string `Failed to patch ${resourceType}/${id}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
        }
    } on fail error e {
        log:printError(string `Error patching ${resourceType}/${id}: ${e.message()}`);
        return r4:createFHIRError(string `Patch operation failed: ${e.message()}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_BAD_REQUEST);
    }
}

// Posts a FHIR AuditEvent to the configured audit service.
// action: C=create R=read U=update D=delete  outcome: "0"=success "8"=failure
isolated function sendAuditEvent(string resourceType, string resourceId, string action,
        string subtype, string outcome, string outcomeDesc) {
    http:Client? httpClient = auditClient;
    if httpClient is () {
        return; // audit service not configured — no-op
    }
    time:Utc now = time:utcNow();
    string recorded = time:utcToString(now);

    json auditPayload = {
        "resourceType": "AuditEvent",
        "type": {
            "system": "http://terminology.hl7.org/CodeSystem/audit-event-type",
            "code": "rest"
        },
        "subtype": [{"system": "http://hl7.org/fhir/restful-interaction", "code": subtype}],
        "action": action,
        "outcome": outcome,
        "outcomeDesc": outcomeDesc,
        "recorded": recorded,
        "agent": [{
            "type": {
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/extra-security-role-type",
                    "code": "humanuser"
                }]
            },
            "who": {"display": serverName},
            "requestor": true
        }],
        "entity": [{
            "type": {
                "system": "http://terminology.hl7.org/CodeSystem/audit-entity-type",
                "code": "2"
            },
            "role": {
                "system": "http://terminology.hl7.org/CodeSystem/object-role",
                "code": "4"
            },
            "what": {"reference": resourceType + (resourceId != "" ? "/" + resourceId : "")}
        }],
        "source": {
            "observer": {"display": serverName},
            "type": [{"system": "http://terminology.hl7.org/CodeSystem/security-source-type", "code": "4"}]
        }
    };

    json|error response = httpClient->/audits.post(auditPayload);
    if response is error {
        log:printWarn("Failed to send audit event.", resourceType = resourceType,
            resourceId = resourceId, action = action, 'error = response);
    }
}

// FHIR validation error details record
public type FHIRValidationErrorDetail record {
    *r4:FHIRErrorDetail;
    [validator:FHIRValidationIssueDetail, validator:FHIRValidationIssueDetail...] issues;
};

// Helper function to convert FHIR issue detail to OperationOutcome issue
isolated function issueDetailToOperationOutcomeIssue(r4:FHIRIssueDetail detail) returns r4:OperationOutcomeIssue {
    r4:OperationOutcomeIssue issueBBE = {
        severity: detail.severity,
        code: detail.code
    };

    r4:CodeableConcept? details = detail.details;
    if details != () {
        issueBBE.details = details;
    }

    string? diagnostic = detail.diagnostic;
    if diagnostic != () {
        issueBBE.diagnostics = string `${diagnostic}`;
    }

    string[]? expression = detail.expression;
    if expression != () {
        issueBBE.expression = expression;
    }

    return issueBBE;
}

isolated function performValidateOperation(string resourceType, Parameters params) returns r4:OperationOutcome|r4:FHIRError {
    log:printDebug(string `${resourceType}: Validate - Start Execution`);
    do {
        // Extract the resource from Parameters
        international401:ParametersParameter[]? parameters = params.'parameter;

        if parameters is () || parameters.length() == 0 {
            return r4:createFHIRError("No parameters provided for validation", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
        }

        json? resourceToValidate = ();

        // Extract resource from parameters
        foreach var param in parameters {
            if param.name == "resource" {
                anydata? resourceData = param.'resource;
                if resourceData is () {
                    return r4:createFHIRError("No resource found in Parameters", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
                }
                resourceToValidate = resourceData.toJson();
            }
        }

        if resourceToValidate is () {
            return r4:createFHIRError("No resource found in Parameters", r4:ERROR, r4:INVALID, httpStatusCode = http:STATUS_BAD_REQUEST);
        }

        // Validate using the FHIR validator
        var validationResult = validator:validate(resourceToValidate);

        r4:OperationOutcome outcome;

        if validationResult is error {
            // Validation failed - extract detailed errors
            log:printInfo(string `${resourceType}: Validation - Failed with errors`);

            FHIRValidationErrorDetail & readonly detail = <FHIRValidationErrorDetail & readonly>validationResult.detail();
            validator:FHIRValidationIssueDetail issues = detail.issues[0];
            r4:FHIRIssueDetail[] issueArray = [];

            string[]? errorInIssue = issues.detailedErrors;
            if errorInIssue != () {
                foreach var i in 0 ..< errorInIssue.length() {
                    r4:FHIRIssueDetail issue = {
                        severity: issues.severity,
                        code: issues.code,
                        diagnostic: errorInIssue[i],
                        expression: issues.expression,
                        details: ()
                    };
                    issueArray.push(issue);
                }
            }

            // Convert FHIRIssueDetail to OperationOutcomeIssue
            r4:OperationOutcomeIssue[] opIssueArray = [];
            foreach var i in 0 ..< issueArray.length() {
                r4:OperationOutcomeIssue opIssue = issueDetailToOperationOutcomeIssue(issueArray[i]);
                opIssueArray.push(opIssue);
            }

            outcome = {
                resourceType: "OperationOutcome",
                issue: opIssueArray
            };
        } else {
            // Validation successful
            log:printInfo(string `${resourceType}: Validation - Success`);
            outcome = {
                resourceType: "OperationOutcome",
                issue: [
                    {
                        severity: "information",
                        code: "informational",
                        diagnostics: "Validation successful"
                    }
                ]
            };
        }

        // Return OperationOutcome directly (HTTP 200)
        return outcome;
    } on fail error e {
        log:printError(string `Error validating ${resourceType}: ${e.message()}`);
        return r4:createFHIRError(string `Validation operation failed: ${e.message()}`, r4:ERROR, r4:PROCESSING, httpStatusCode = http:STATUS_INTERNAL_SERVER_ERROR);
    }
}

service /fhir/r4/Endpoint on new fhirr4:Listener(config = r4_api_config:endpointApiConfig) {
    isolated resource function get .(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceSearch("Endpoint", fhirContext);
    }

    isolated resource function get [string id](r4:FHIRContext fhirContext) returns Endpoint|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceRead("Endpoint", id);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Endpoint, "Endpoint");
        return <Endpoint|r4:OperationOutcome|r4:FHIRError>converted;
    }

    isolated resource function get [string id]/_history/[string vid](r4:FHIRContext fhirContext) returns Endpoint|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceVersionRead("Endpoint", id, vid);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Endpoint, "Endpoint");
        return <Endpoint|r4:OperationOutcome|r4:FHIRError>converted;
    }

    isolated resource function post .(r4:FHIRContext fhirContext, Endpoint endpoint) returns Endpoint|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceCreate("Endpoint", endpoint.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Endpoint, "Endpoint");
        return <Endpoint|r4:OperationOutcome|r4:FHIRError>converted;
    }

    isolated resource function put [string id](r4:FHIRContext fhirContext, Endpoint endpoint) returns Endpoint|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceUpdate("Endpoint", id, endpoint.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Endpoint, "Endpoint");
        return <Endpoint|r4:OperationOutcome|r4:FHIRError>converted;
    }

    isolated resource function patch [string id](r4:FHIRContext fhirContext, json patch) returns Endpoint|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourcePatch("Endpoint", id, patch);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Endpoint, "Endpoint");
        return <Endpoint|r4:OperationOutcome|r4:FHIRError>converted;
    }

    isolated resource function delete [string id](r4:FHIRContext fhirContext) returns r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceDelete("Endpoint", id);
    }

    // Retrieve the update history for a particular resource.
    isolated resource function get [string id]/_history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceHistory("Endpoint", id);
    }

    // Retrieve the update history for all resources.
    isolated resource function get _history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performAllResourceHistory("Endpoint");
    }

    // Validate operation - accepts Parameters resource containing the resource to validate
    isolated resource function post \$validate(r4:FHIRContext fhirContext, Parameters params) returns r4:OperationOutcome|r4:FHIRError {
        return performValidateOperation("Endpoint", params);
    }
}

service /fhir/r4/Organization on new fhirr4:Listener(config = r4_api_config:organizationApiConfig) {
    // Search for resources using /Organization?params
    isolated resource function get .(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceSearch("Organization", fhirContext);
    }

    // Read the current state of single resource based on its id.
    isolated resource function get [string id](r4:FHIRContext fhirContext) returns Organization|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceRead("Organization", id);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Organization, "Organization");
        return <Organization|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Read the state of a specific version of a resource based on its id.
    isolated resource function get [string id]/_history/[string vid](r4:FHIRContext fhirContext) returns Organization|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceVersionRead("Organization", id, vid);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Organization, "Organization");
        return <Organization|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Create a new resource.
    isolated resource function post .(r4:FHIRContext fhirContext, Organization organization) returns Organization|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceCreate("Organization", organization.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Organization, "Organization");
        return <Organization|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource completely.
    isolated resource function put [string id](r4:FHIRContext fhirContext, Organization organization) returns Organization|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceUpdate("Organization", id, organization.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Organization, "Organization");
        return <Organization|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource partially.
    isolated resource function patch [string id](r4:FHIRContext fhirContext, json patch) returns Organization|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourcePatch("Organization", id, patch);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Organization, "Organization");
        return <Organization|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Delete a resource.
    isolated resource function delete [string id](r4:FHIRContext fhirContext) returns r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceDelete("Organization", id);
    }

    // Retrieve the update history for a particular resource.
    isolated resource function get [string id]/_history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceHistory("Organization", id);
    }

    // Retrieve the update history for all resources.
    isolated resource function get _history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performAllResourceHistory("Organization");
    }

    // Validate operation - accepts Parameters resource containing the resource to validate
    isolated resource function post \$validate(r4:FHIRContext fhirContext, Parameters params) returns r4:OperationOutcome|r4:FHIRError {
        return performValidateOperation("Organization", params);
    }
}

service /fhir/r4/OrganizationAffiliation on new fhirr4:Listener(config = r4_api_config:organizationaffiliationApiConfig) {
    // Search for resources
    isolated resource function get .(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceSearch("OrganizationAffiliation", fhirContext);
    }

    // Read the current state of single resource based on its id.
    isolated resource function get [string id](r4:FHIRContext fhirContext) returns OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceRead("OrganizationAffiliation", id);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, OrganizationAffiliation, "OrganizationAffiliation");
        return <OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Read the state of a specific version of a resource based on its id.
    isolated resource function get [string id]/_history/[string vid](r4:FHIRContext fhirContext) returns OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceVersionRead("OrganizationAffiliation", id, vid);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, OrganizationAffiliation, "OrganizationAffiliation");
        return <OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Create a new resource.
    isolated resource function post .(r4:FHIRContext fhirContext, OrganizationAffiliation organizationaffiliation) returns OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceCreate("OrganizationAffiliation", organizationaffiliation.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, OrganizationAffiliation, "OrganizationAffiliation");
        return <OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource completely.
    isolated resource function put [string id](r4:FHIRContext fhirContext, OrganizationAffiliation organizationaffiliation) returns OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceUpdate("OrganizationAffiliation", id, organizationaffiliation.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, OrganizationAffiliation, "OrganizationAffiliation");
        return <OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource partially.
    isolated resource function patch [string id](r4:FHIRContext fhirContext, json patch) returns OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourcePatch("OrganizationAffiliation", id, patch);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, OrganizationAffiliation, "OrganizationAffiliation");
        return <OrganizationAffiliation|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Delete a resource.
    isolated resource function delete [string id](r4:FHIRContext fhirContext) returns r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceDelete("OrganizationAffiliation", id);
    }

    // Retrieve the update history for a particular resource.
    isolated resource function get [string id]/_history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceHistory("OrganizationAffiliation", id);
    }

    // Retrieve the update history for all resources.
    isolated resource function get _history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performAllResourceHistory("OrganizationAffiliation");
    }

    // Validate operation - accepts Parameters resource containing the resource to validate
    isolated resource function post \$validate(r4:FHIRContext fhirContext, Parameters params) returns r4:OperationOutcome|r4:FHIRError {
        return performValidateOperation("OrganizationAffiliation", params);
    }
}

// // # HealthcareService API                                                                                                          #
// 
service /fhir/r4/HealthcareService on new fhirr4:Listener(config = r4_api_config:healthcareserviceApiConfig) {
    // Search for resources
    isolated resource function get .(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceSearch("HealthcareService", fhirContext);
    }

    // Read the current state of single resource based on its id.
    isolated resource function get [string id](r4:FHIRContext fhirContext) returns HealthcareService|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceRead("HealthcareService", id);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, HealthcareService, "HealthcareService");
        return <HealthcareService|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Read the state of a specific version of a resource based on its id.
    isolated resource function get [string id]/_history/[string vid](r4:FHIRContext fhirContext) returns HealthcareService|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceVersionRead("HealthcareService", id, vid);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, HealthcareService, "HealthcareService");
        return <HealthcareService|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Create a new resource.
    isolated resource function post .(r4:FHIRContext fhirContext, HealthcareService healthcareservice) returns HealthcareService|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceCreate("HealthcareService", healthcareservice.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, HealthcareService, "HealthcareService");
        return <HealthcareService|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource completely.
    isolated resource function put [string id](r4:FHIRContext fhirContext, HealthcareService healthcareservice) returns HealthcareService|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceUpdate("HealthcareService", id, healthcareservice.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, HealthcareService, "HealthcareService");
        return <HealthcareService|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource partially.
    isolated resource function patch [string id](r4:FHIRContext fhirContext, json patch) returns HealthcareService|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourcePatch("HealthcareService", id, patch);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, HealthcareService, "HealthcareService");
        return <HealthcareService|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Delete a resource.
    isolated resource function delete [string id](r4:FHIRContext fhirContext) returns r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceDelete("HealthcareService", id);
    }

    // Retrieve the update history for a particular resource.
    isolated resource function get [string id]/_history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceHistory("HealthcareService", id);
    }

    // Retrieve the update history for all resources.
    isolated resource function get _history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performAllResourceHistory("HealthcareService");
    }

    // Validate operation - accepts Parameters resource containing the resource to validate
    isolated resource function post \$validate(r4:FHIRContext fhirContext, Parameters params) returns r4:OperationOutcome|r4:FHIRError {
        return performValidateOperation("HealthcareService", params);
    }
}

// // # Location API                                                                                                          #
// 
service /fhir/r4/Location on new fhirr4:Listener(config = r4_api_config:locationApiConfig) {
    // Search for resources using /Location?params
    isolated resource function get .(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceSearch("Location", fhirContext);
    }

    // Read the current state of single resource based on its id.
    isolated resource function get [string id](r4:FHIRContext fhirContext) returns Location|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceRead("Location", id);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Location, "Location");
        return <Location|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Read the state of a specific version of a resource based on its id.
    isolated resource function get [string id]/_history/[string vid](r4:FHIRContext fhirContext) returns Location|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti90Enabled, "ITI-90");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceVersionRead("Location", id, vid);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Location, "Location");
        return <Location|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Create a new resource.
    isolated resource function post .(r4:FHIRContext fhirContext, Location location) returns Location|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceCreate("Location", location.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Location, "Location");
        return <Location|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource completely.
    isolated resource function put [string id](r4:FHIRContext fhirContext, Location location) returns Location|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourceUpdate("Location", id, location.toJson());
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Location, "Location");
        return <Location|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Update the current state of a resource partially.
    isolated resource function patch [string id](r4:FHIRContext fhirContext, json patch) returns Location|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        any|r4:OperationOutcome|r4:FHIRError result = performResourcePatch("Location", id, patch);
        anydata|r4:OperationOutcome|r4:FHIRError converted = convertToTypedResource(result, Location, "Location");
        return <Location|r4:OperationOutcome|r4:FHIRError>converted;
    }

    // Delete a resource.
    isolated resource function delete [string id](r4:FHIRContext fhirContext) returns r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti130Enabled, "ITI-130");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceDelete("Location", id);
    }

    // Retrieve the update history for a particular resource.
    isolated resource function get [string id]/_history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performResourceHistory("Location", id);
    }

    // Retrieve the update history for all resources.
    isolated resource function get _history(r4:FHIRContext fhirContext) returns r4:Bundle|r4:OperationOutcome|r4:FHIRError {
        r4:FHIRError? txCheck = checkTransactionEnabled(iti91Enabled, "ITI-91");
        if txCheck is r4:FHIRError { return txCheck; }
        return performAllResourceHistory("Location");
    }

    // Validate operation - accepts Parameters resource containing the resource to validate
    isolated resource function post \$validate(r4:FHIRContext fhirContext, Parameters params) returns r4:OperationOutcome|r4:FHIRError {
        return performValidateOperation("Location", params);
    }
}

